
(executable
 (name ftest)
 ;; (libraries )
 
 ;; Disable some warnings
 ;; (flags (:standard -w -6))

 ;; Link to executable in main dir

 
 )

 (executable
  (name cricket_solver)
  (libraries str)
 
 )

 (executable
  (name cr1)
  (libraries str)
 
 )

 (executable
  (name ftest11)
  (libraries str) 
 
 )


