(* Read a graph from a file,
 * Write a graph to a file. *)

open Graph

type path = string

(* Values are read as strings. *)
val from_file: path -> string graph

(* Similarly, we write only a string graph.
 * If necessary, use gmap (to be written by you) to prepare the input graph. *)
val write_file: path -> string graph -> unit


(* The format of files is compatible with the files generated by:
   https://algorithms.discrete.ma.tum.de/graph-algorithms/flow-ford-fulkerson/index_en.html
*)


(* val export : string graph -> string -> unit *)

(** [export path graph] écrit le graphe [graph] dans un fichier au format DOT. 
    Le fichier est sauvegardé avec le chemin [path] et l'extension ".dot".

    @param path Le chemin (sans extension) où le fichier sera sauvegardé.
    @param graph Le graphe à écrire, dont les nœuds et arcs sont définis dans le module Graph.
    @raise Sys_error Si le fichier ne peut pas être ouvert ou écrit.
    @raise Invalid_argument Si le graphe contient des données invalides. *)
val export : string -> string graph -> unit
